# Generated by Django 3.1.2 on 2021-03-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/profile_pic_default.png', upload_to='images/'),
        ),
    ]
